import { createFileRoute } from "@tanstack/react-router";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { ArrowRight, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { PageIntro, SiteShell } from "@/components/site-shell";
import { WHATSAPP_PRIMARY } from "@/lib/site-data";
const schema=z.object({ownerName:z.string().trim().min(2,"Nama minimal 2 karakter").max(100),phone:z.string().trim().regex(/^[+0-9][0-9\s-]{7,22}$/,"Nomor WhatsApp tidak valid"),brand:z.enum(["Volkswagen","Audi","Mini Cooper"]),modelYear:z.string().trim().min(2,"Masukkan model dan tahun").max(100),licensePlate:z.string().trim().min(2,"Masukkan nomor polisi").max(20),mileage:z.coerce.number().int().min(0,"Kilometer tidak valid").max(2000000),service:z.string().trim().min(10,"Jelaskan kebutuhan minimal 10 karakter").max(1500)});
type BookingValues=z.infer<typeof schema>;
export const Route=createFileRoute("/booking")({head:()=>({meta:[{title:"Booking Servis via WhatsApp — AxcMotora"},{name:"description",content:"Kirim detail booking servis Volkswagen, Audi atau Mini Cooper langsung ke WhatsApp AxcMotora."},{property:"og:title",content:"Booking Servis — AxcMotora"},{property:"og:description",content:"Isi detail kendaraan dan lanjutkan konsultasi langsung melalui WhatsApp."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:BookingPage});
function BookingPage(){const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<BookingValues>({resolver:zodResolver(schema),defaultValues:{brand:"Volkswagen"}});const submit=(values:BookingValues)=>{const message=["Halo AxcMotora, saya ingin melakukan booking servis.","",`Nama Pemilik: ${values.ownerName}`,`No. WhatsApp: ${values.phone}`,`Kendaraan: ${values.brand} ${values.modelYear}`,`Nomor Polisi: ${values.licensePlate.toUpperCase()}`,`Kilometer: ${values.mileage.toLocaleString("id-ID")} KM`,"",`Keluhan / Layanan:",values.service,"","Mohon konfirmasi ketersediaan jadwal. Terima kasih."].join("\n");window.open(`https://wa.me/${WHATSAPP_PRIMARY}?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")};return <SiteShell><PageIntro eyebrow="Booking Servis" title="Ceritakan kondisi kendaraan Anda." description="Lengkapi detail berikut. Setelah dikonfirmasi, percakapan akan dilanjutkan langsung melalui WhatsApp AxcMotora."/><section><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 lg:grid-cols-[0.7fr_1.3fr] lg:px-6 lg:py-24"><aside><MessageCircle className="size-8 text-primary"/><h2 className="mt-6 font-display text-2xl font-semibold">Langsung ke tim workshop.</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Formulir ini tidak menghitung biaya. Detail Anda akan disusun menjadi pesan WhatsApp agar tim kami dapat menindaklanjuti kebutuhan dan jadwal.</p></aside><form onSubmit={handleSubmit(submit)} className="grid gap-6 border border-border bg-card p-6 sm:grid-cols-2 lg:p-10"> <Field label="Nama Pemilik" error={errors.ownerName?.message}><Input {...register("ownerName")} autoComplete="name"/></Field><Field label="No. Telepon / WhatsApp" error={errors.phone?.message}><Input {...register("phone")} inputMode="tel" autoComplete="tel"/></Field><Field label="Merek Kendaraan" error={errors.brand?.message}><select {...register("brand")} className="form-select"><option>Volkswagen</option><option>Audi</option><option>Mini Cooper</option></select></Field><Field label="Model / Tahun" error={errors.modelYear?.message}><Input {...register("modelYear")} placeholder="Contoh: Golf GTI / 2019"/></Field><Field label="Nomor Polisi" error={errors.licensePlate?.message}><Input {...register("licensePlate")} className="uppercase"/></Field><Field label="Kilometer (KM)" error={errors.mileage?.message}><Input {...register("mileage")} type="number" min="0"/></Field><div className="sm:col-span-2"><Field label="Keluhan atau Layanan" error={errors.service?.message}><Textarea {...register("service")} rows={6} placeholder="Jelaskan gejala, riwayat singkat, atau layanan yang dibutuhkan..."/></Field></div><div className="sm:col-span-2"><Button type="submit" size="lg" disabled={isSubmitting}>Konfirmasi Booking <ArrowRight/></Button></div></form></div></section></SiteShell>}
function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}{error&&<p className="text-xs text-destructive">{error}</p>}</div>}
