import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, CheckCircle2, Clock3, Instagram, MapPin, MessageCircle, ShieldCheck, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/reveal";
import { SiteShell } from "@/components/site-shell";
import { ADDRESS, INSTAGRAM_URL, services, WHATSAPP_PRIMARY } from "@/lib/site-data";
import heroImage from "@/assets/axcmotora-workshop.jpg";
import diagnosticImage from "@/assets/axcmotora-diagnostics.jpg";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "AxcMotora — Spesialis VW, Audi & Mini Cooper Tangerang" }, { name: "description", content: "Servis spesialis Volkswagen, Audi dan Mini Cooper di Tangerang: diagnostik, perawatan, transmisi, kelistrikan dan tuning." }, { property: "og:title", content: "AxcMotora — European Auto Specialist" }, { property: "og:description", content: "Precision specialist care untuk Volkswagen, Audi & Mini Cooper di Tangerang." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: HomePage });

function HomePage() { return <SiteShell>
  <section className="relative overflow-hidden border-b border-border bg-surface-subtle">
    <img src={heroImage} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover opacity-15 lg:hidden" />
    <div className="absolute inset-0 bg-hero-overlay lg:hidden" aria-hidden="true" />
    <div className="relative mx-auto grid max-w-7xl items-center gap-10 px-4 py-14 lg:min-h-[720px] lg:grid-cols-[0.9fr_1.1fr] lg:px-6 lg:py-20">
      <Reveal className="relative z-10">
        <div className="inline-flex items-center gap-3 border border-primary/40 bg-primary/10 px-4 py-2 text-xs font-bold uppercase text-primary"><span className="size-2 animate-status-pulse bg-primary" /> Booking Servis Tersedia</div>
        <h1 className="mt-8 max-w-3xl font-display text-5xl leading-[0.98] md:text-7xl lg:text-[5.25rem]">Precision <span className="text-primary">Specialist</span> Care.</h1>
        <p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Perawatan, diagnostik, dan tuning khusus Volkswagen, Audi & Mini Cooper di Tangerang.</p>
        <div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button size="lg" asChild><Link to="/booking">Booking Servis <ArrowRight /></Link></Button><Button size="lg" variant="outline" asChild><a href={`https://wa.me/${WHATSAPP_PRIMARY}`} target="_blank" rel="noreferrer"><MessageCircle /> Konsultasi WhatsApp</a></Button></div>
        <div className="mt-10 grid grid-cols-3 border-y border-border py-5 text-center sm:text-left"><div><p className="font-display text-xl text-foreground">VW</p><p className="mt-1 text-xs uppercase text-muted-foreground">Specialist</p></div><div className="border-x border-border px-4"><p className="font-display text-xl text-foreground">AUDI</p><p className="mt-1 text-xs uppercase text-muted-foreground">Specialist</p></div><div className="pl-4"><p className="font-display text-xl text-foreground">MINI</p><p className="mt-1 text-xs uppercase text-muted-foreground">Specialist</p></div></div>
      </Reveal>
      <Reveal delay={120} className="relative">
        <div className="absolute -inset-4 border border-primary/20" aria-hidden="true" />
        <div className="group relative border border-border bg-card p-3"><div className="relative overflow-hidden"><img src={heroImage} alt="Workshop spesialis AxcMotora dengan kendaraan Eropa" width={1920} height={1088} className="aspect-[4/3] w-full object-cover opacity-80 transition duration-700 group-hover:scale-[1.03] group-hover:opacity-100" /><div className="absolute inset-0 bg-hero-overlay" /><div className="absolute bottom-0 left-0 right-0 grid grid-cols-2 gap-px bg-border"><div className="bg-background/90 p-4 backdrop-blur-md"><ShieldCheck className="size-5 text-primary" /><p className="mt-2 text-xs font-bold uppercase">Diagnostik Presisi</p></div><div className="bg-background/90 p-4 backdrop-blur-md"><Wrench className="size-5 text-primary" /><p className="mt-2 text-xs font-bold uppercase">Spesialis Eropa</p></div></div></div></div>
      </Reveal>
    </div>
  </section>
  <section className="border-b border-border"><div className="mx-auto max-w-7xl px-4 py-20 lg:px-6 lg:py-28"><Reveal className="grid gap-6 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="section-kicker">Spesialisasi Kami</p><h2 className="section-title">Satu workshop.<br />Lima keahlian inti.</h2></div><div className="flex flex-col items-start justify-between gap-5 lg:flex-row lg:items-end"><p className="section-copy mt-0">Kami memahami karakter, sistem elektronik, dan kebutuhan perawatan Volkswagen, Audi, serta Mini Cooper.</p><Button variant="outline" asChild><Link to="/layanan">Semua layanan <ArrowRight /></Link></Button></div></Reveal><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{services.map((service, index) => <Reveal key={service.title} delay={index * 90} className={index < 2 ? "lg:col-span-3" : "lg:col-span-2"}><article className="group relative h-full min-h-64 overflow-hidden border border-border bg-card p-7 transition duration-300 hover:-translate-y-1 hover:border-primary/70"><span className="absolute right-5 top-4 font-display text-4xl text-foreground/5">0{index + 1}</span><service.icon className="size-7 text-primary" /><h3 className="mt-12 max-w-xs font-display text-xl leading-tight">{service.title}</h3><p className="mt-4 text-sm leading-6 text-muted-foreground">{service.description}</p><div className="absolute bottom-0 left-0 h-1 w-0 bg-primary transition-all duration-500 group-hover:w-full" /></article></Reveal>)}</div></div></section>
  <section className="bg-surface-subtle"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 lg:grid-cols-[1.15fr_0.85fr] lg:items-center lg:px-6 lg:py-28"><Reveal className="relative"><div className="absolute -bottom-4 -left-4 size-24 border-b-2 border-l-2 border-primary" /><img src={diagnosticImage} alt="Teknisi AxcMotora melakukan diagnostik kendaraan" loading="lazy" width={1408} height={1008} className="relative aspect-[7/5] w-full border border-border object-cover" /></Reveal><Reveal delay={140}><p className="section-kicker">Proses AxcMotora</p><h2 className="section-title">Diagnosis tepat sebelum tindakan.</h2><p className="section-copy">Setiap pengerjaan dimulai dari pemeriksaan yang jelas, komunikasi transparan, dan perhatian terhadap detail.</p><ul className="mt-8 divide-y divide-border border-y border-border">{["Peralatan diagnostik kendaraan Eropa", "Pengerjaan fokus untuk VW, Audi & Mini Cooper", "Konsultasi langsung dengan tim workshop"].map(item => <li key={item} className="flex items-center gap-3 py-4 text-sm font-semibold uppercase"><CheckCircle2 className="size-4 shrink-0 text-primary" />{item}</li>)}</ul></Reveal></div></section>
  <section className="border-y border-border"><div className="mx-auto grid max-w-7xl gap-px bg-border md:grid-cols-3"><Reveal><Link to="/kontak" className="group block min-h-72 bg-background p-8 transition-colors hover:bg-card"><MapPin className="size-6 text-primary" /><h2 className="mt-8 font-display text-2xl">Workshop Tangerang</h2><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">{ADDRESS}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold uppercase text-primary">Lihat kontak <ArrowRight className="transition-transform group-hover:translate-x-1" /></span></Link></Reveal><Reveal delay={100}><div className="min-h-72 bg-background p-8"><Clock3 className="size-6 text-primary" /><h2 className="mt-8 font-display text-2xl">Jam Operasional</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Senin sampai Sabtu<br />08:30 – 17:00 WIB</p></div></Reveal><Reveal delay={200}><a href={INSTAGRAM_URL} target="_blank" rel="noreferrer" className="group block min-h-72 bg-background p-8 transition-colors hover:bg-card"><Instagram className="size-6 text-primary" /><h2 className="mt-8 font-display text-2xl">@AxcMotora</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Aktivitas workshop, proyek terkini, dan detail pengerjaan kami.</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-bold uppercase text-primary">Buka Instagram <ArrowRight className="transition-transform group-hover:translate-x-1" /></span></a></Reveal></div></section>
</SiteShell>; }
