/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as SparepartRouteImport } from './routes/sparepart'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const SparepartRoute = SparepartRouteImport.update({
  id: '/sparepart',
  path: '/sparepart',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/sparepart': typeof SparepartRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/sparepart': typeof SparepartRoute
  '/tentang': typeof TentangRoute
  '/admin': typeof AuthenticatedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/sparepart': typeof SparepartRoute
  '/tentang': typeof TentangRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/booking'
    | '/kontak'
    | '/layanan'
    | '/sparepart'
    | '/tentang'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/booking'
    | '/kontak'
    | '/layanan'
    | '/sparepart'
    | '/tentang'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/booking'
    | '/kontak'
    | '/layanan'
    | '/sparepart'
    | '/tentang'
    | '/_authenticated/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  SparepartRoute: typeof SparepartRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sparepart': {
      id: '/sparepart'
      path: '/sparepart'
      fullPath: '/sparepart'
      preLoaderRoute: typeof SparepartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  SparepartRoute: SparepartRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
